name: Publish release
on:
  push:
    branches:
      - feature/V2-4855-create-custom-version
permissions: write-all

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build the `pdfjs` generic folder
        run: npx gulp generic

      - name: Configure npm
        working-directory: ./build/generic
        run: echo "@closd:registry=https://npm.pkg.github.com" > ~/.npmrc

      - name: Publish to GitHub Packages Registry
        run: npm publish ./build/generic --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
